### ISSUE TITLE
Gatsby Cookie Notice and Security

### ISSUE THREAD

**Issue by sandradeb** [florent6001/gatsby-cookie-notice#1]
Hello, I have added "gatsby-cookie-notice" to my website. But I don't see any security settings like SameSite "strict", Set-Cookie "Secure", etc. Is there any way to secure cookies with "gatsby-cookie-notice" ? 
Thank you, this helps a lot!

**Comment by florentvdry** [comment]
J'ai vu que tu étais française avec une simple recherche google, donc je vais répondre en français.

Gatsby-cookie-notice est lié au plugin gatsby-plugin-gdpr-cookies, le plugin que j'ai développé affiche uniquement la bannière de consentement et permet de personnaliser les cookies que l'utilisateur accepte / refuse.

Le stockage des cookies n'est en conséquence pas fait par moi, mais par le plugin gatsby-plugin-gdpr-cookies auquel je suis lié.
Je t'invite à te rapprocher de ce fait de l'autre plugin.

Je reste disponible si tu as d'autre questions.

**Comment by sandradeb** [comment]
Ok compris, je vais voir du côté de gatsby-plugin-gdpr-cookies. Merci pour cette réactivité ! :)
Bonne journée

**Comment by florentvdry** [comment]
Après vérification, je t'ai dis des conneries,
la ligne ou je met le cookie est la ligne 64 de ce fichier :
https://github.com/florent6001/gatsby-cookie-notice/blob/master/src/lib/components/CookieNotice.js

C'est globalement le fichier de la librairie, tu peux l'utiliser et modifier la ligne si tu le souhaite.

**Comment by florentvdry** [comment]
Également ligne 83 pour si la personne personnalise les cookies qu'elle accepte / refuse @sandradeb

**Comment by sandradeb** [comment]
Merci pour ton retour, mais je suis passé par un autre plugin du coup, moins bien sur certains points, mais c'était plus simple… Super début de plugin en tout cas, hâte de le voir évoluer. 
Bonne journée !
